/* 
* This file is part of STiD135 OXFORD LLA 
* 
* Copyright (c) <2014>-<2018>, STMicroelectronics - All Rights Reserved 
* Author(s): Mathias Hilaire (mathias.hilaire@st.com), Thierry Delahaye (thierry.delahaye@st.com) for STMicroelectronics. 
* 
* License terms: BSD 3-clause "New" or "Revised" License. 
* 
* Redistribution and use in source and binary forms, with or without 
* modification, are permitted provided that the following conditions are met: 
* 
* 1. Redistributions of source code must retain the above copyright notice, this 
* list of conditions and the following disclaimer. 
* 
* 2. Redistributions in binary form must reproduce the above copyright notice, 
* this list of conditions and the following disclaimer in the documentation 
* and/or other materials provided with the distribution. 
* 
* 3. Neither the name of the copyright holder nor the names of its contributors 
* may be used to endorse or promote products derived from this software 
* without specific prior written permission. 
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
* FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
* DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
* 
*/ 
#ifndef _C8CODEW_RFMUX_REG_INIT_H
#define _C8CODEW_RFMUX_REG_INIT_H

/* -------------------------------------------------------------------------
 * File name  : c8codew_rfmux_reg_init.h
 * File type  : C header file
 * -------------------------------------------------------------------------
 * Description:  Register map constants
 * Generated by spirit2regtest v2.24_alpha3
 * -------------------------------------------------------------------------
 */


/* Register map constants */

/* RFMUX0 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX0                                0x00000000
#define RC8CODEW_C8CODEW_RFMUX_RFMUX0__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX0_RFMUX_DEMOD_SEL_1__MASK        0x03      

/* RFMUX1 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX1                                0x00000001
#define RC8CODEW_C8CODEW_RFMUX_RFMUX1__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX1_RFMUX_DEMOD_SEL_2__MASK        0x03      

/* RFMUX2 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX2                                0x00000002
#define RC8CODEW_C8CODEW_RFMUX_RFMUX2__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX2_RFMUX_DEMOD_SEL_3__MASK        0x03      

/* RFMUX3 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX3                                0x00000003
#define RC8CODEW_C8CODEW_RFMUX_RFMUX3__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX3_RFMUX_DEMOD_SEL_4__MASK        0x03      

/* RFMUX4 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX4                                0x00000004
#define RC8CODEW_C8CODEW_RFMUX_RFMUX4__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX4_RFMUX_DEMOD_SEL_5__MASK        0x03      

/* RFMUX5 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX5                                0x00000005
#define RC8CODEW_C8CODEW_RFMUX_RFMUX5__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX5_RFMUX_DEMOD_SEL_6__MASK        0x03      

/* RFMUX6 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX6                                0x00000006
#define RC8CODEW_C8CODEW_RFMUX_RFMUX6__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX6_RFMUX_DEMOD_SEL_7__MASK        0x03      

/* RFMUX7 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUX7                                0x00000007
#define RC8CODEW_C8CODEW_RFMUX_RFMUX7__DEFAULT                       0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUX7_RFMUX_DEMOD_SEL_8__MASK        0x03      

/* RFMUXRV0 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV0                              0x00000008
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV0__DEFAULT                     0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUXRV0_RFMUX_AGCRF_SEL_1__MASK      0x07      

/* RFMUXRV1 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV1                              0x00000009
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV1__DEFAULT                     0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUXRV1_RFMUX_AGCRF_SEL_2__MASK      0x07      

/* RFMUXRV2 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV2                              0x0000000a
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV2__DEFAULT                     0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUXRV2_RFMUX_AGCRF_SEL_3__MASK      0x07      

/* RFMUXRV3 */
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV3                              0x0000000b
#define RC8CODEW_C8CODEW_RFMUX_RFMUXRV3__DEFAULT                     0x0       
#define FC8CODEW_C8CODEW_RFMUX_RFMUXRV3_RFMUX_AGCRF_SEL_4__MASK      0x07      

/* AGCRFXOR */
#define RC8CODEW_C8CODEW_RFMUX_AGCRFXOR                              0x00000010
#define RC8CODEW_C8CODEW_RFMUX_AGCRFXOR__DEFAULT                     0x0       
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCRF1_XOR__MASK             0x01      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCRF2_XOR__MASK             0x02      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCRF3_XOR__MASK             0x04      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCRF4_XOR__MASK             0x08      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCBB1_XOR__MASK             0x10      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCBB2_XOR__MASK             0x20      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCBB3_XOR__MASK             0x40      
#define FC8CODEW_C8CODEW_RFMUX_AGCRFXOR_AGCBB4_XOR__MASK             0x80      


/* Number of registers */
#define C8CODEW_C8CODEW_RFMUX_REG_NBREGS                             13        

/* Number of fields */
#define C8CODEW_C8CODEW_RFMUX_REG_NBFIELDS                           20        



#endif /* #ifndef _C8CODEW_RFMUX_REG_INIT_H */
