/* 
* This file is part of STiD135 OXFORD LLA 
* 
* Copyright (c) <2014>-<2018>, STMicroelectronics - All Rights Reserved 
* Author(s): Mathias Hilaire (mathias.hilaire@st.com), Thierry Delahaye (thierry.delahaye@st.com) for STMicroelectronics. 
* 
* License terms: BSD 3-clause "New" or "Revised" License. 
* 
* Redistribution and use in source and binary forms, with or without 
* modification, are permitted provided that the following conditions are met: 
* 
* 1. Redistributions of source code must retain the above copyright notice, this 
* list of conditions and the following disclaimer. 
* 
* 2. Redistributions in binary form must reproduce the above copyright notice, 
* this list of conditions and the following disclaimer in the documentation 
* and/or other materials provided with the distribution. 
* 
* 3. Neither the name of the copyright holder nor the names of its contributors 
* may be used to endorse or promote products derived from this software 
* without specific prior written permission. 
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
* FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
* DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
* 
*/ 
#ifndef _C8CODEW_PATH_CTRL_GEN_REG_INIT_H
#define _C8CODEW_PATH_CTRL_GEN_REG_INIT_H

/* -------------------------------------------------------------------------
 * File name  : c8codew_path_ctrl_gen_reg_init.h
 * File type  : C header file
 * -------------------------------------------------------------------------
 * Description:  Register map constants
 * Generated by spirit2regtest v2.24_alpha3
 * -------------------------------------------------------------------------
 */


/* Register map constants */

/* FRESGEN */
#define RC8CODEW_C8CODEW_PATH_CTRL_GEN_FRESGEN                       0x00000000
#define RC8CODEW_C8CODEW_PATH_CTRL_GEN_FRESGEN__DEFAULT              0x0       
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_FRESGEN_FRESTS__MASK          0x01      
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_FRESGEN_FRESMAS__MASK         0x02      
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_FRESGEN_FRESINT__MASK         0x04      
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_FRESGEN_FRESI2C__MASK         0x08      

/* TBUSSEL */
#define RC8CODEW_C8CODEW_PATH_CTRL_GEN_TBUSSEL                       0x00000010
#define RC8CODEW_C8CODEW_PATH_CTRL_GEN_TBUSSEL__DEFAULT              0x0       
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_TBUSSEL_TBUS_SELECT__MASK     0x0F      

/* BYPASSEN */
#define RC8CODEW_C8CODEW_PATH_CTRL_GEN_BYPASSEN                      0x00000011
#define RC8CODEW_C8CODEW_PATH_CTRL_GEN_BYPASSEN__DEFAULT             0x0       
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_BYPASSEN_DEMOD_BYP__MASK      0x01      
#define FC8CODEW_C8CODEW_PATH_CTRL_GEN_BYPASSEN_DVBS2FEC_BYPASS__MASK 0x02      


/* Number of registers */
#define C8CODEW_C8CODEW_PATH_CTRL_GEN_REG_NBREGS                     3         

/* Number of fields */
#define C8CODEW_C8CODEW_PATH_CTRL_GEN_REG_NBFIELDS                   7         



#endif /* #ifndef _C8CODEW_PATH_CTRL_GEN_REG_INIT_H */
