/* 
* This file is part of STiD135 OXFORD LLA 
* 
* Copyright (c) <2014>-<2018>, STMicroelectronics - All Rights Reserved 
* Author(s): Mathias Hilaire (mathias.hilaire@st.com), Thierry Delahaye (thierry.delahaye@st.com) for STMicroelectronics. 
* 
* License terms: BSD 3-clause "New" or "Revised" License. 
* 
* Redistribution and use in source and binary forms, with or without 
* modification, are permitted provided that the following conditions are met: 
* 
* 1. Redistributions of source code must retain the above copyright notice, this 
* list of conditions and the following disclaimer. 
* 
* 2. Redistributions in binary form must reproduce the above copyright notice, 
* this list of conditions and the following disclaimer in the documentation 
* and/or other materials provided with the distribution. 
* 
* 3. Neither the name of the copyright holder nor the names of its contributors 
* may be used to endorse or promote products derived from this software 
* without specific prior written permission. 
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
* FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
* DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
* 
*/ 
#ifndef _C8IRQ_MERGER_TOP_REG_INIT_H
#define _C8IRQ_MERGER_TOP_REG_INIT_H

/* -------------------------------------------------------------------------
 * File name  : c8irq_merger_top_reg_init.h
 * File type  : C header file
 * -------------------------------------------------------------------------
 * Description:  Register map constants
 * Generated by spirit2regtest v2.24_alpha3
 * -------------------------------------------------------------------------
 */


/* Register map constants */

/* IRQ_POL */
#define RSTID135_C8IRQ_MERGER_TOP_IRQ_POL                            0x00000000
#define RSTID135_C8IRQ_MERGER_TOP_IRQ_POL__DEFAULT                   0x0       
#define FSTID135_C8IRQ_MERGER_TOP_IRQ_POL_IRQ_POL__MASK              0xFFFFFFFF

/* IRQ_VAL */
#define RSTID135_C8IRQ_MERGER_TOP_IRQ_VAL                            0x00000004
#define RSTID135_C8IRQ_MERGER_TOP_IRQ_VAL__DEFAULT                   0x0       
#define FSTID135_C8IRQ_MERGER_TOP_IRQ_VAL_IRQ_VAL__MASK              0xFFFFFFFF


/* Number of registers */
#define STID135_C8IRQ_MERGER_TOP_REG_NBREGS                          2         

/* Number of fields */
#define STID135_C8IRQ_MERGER_TOP_REG_NBFIELDS                        2         



#endif /* #ifndef _C8IRQ_MERGER_TOP_REG_INIT_H */
